### ISSUE TITLE
SwiftyBeaver

### ISSUE THREAD

**Issue by IsaiahJTurner** [neoneye/SwiftSnakeEngine#1]
Your project uses SwiftyBeaver. SwiftyBeaver has security vulnerabilities that you may wish to address. Consider removing SwiftyBeaver if your app transmits PII. https://github.com/SwiftyBeaver/SwiftyBeaver/issues/453

**Comment by neoneye** [comment]
Irrelevant spam. I don't use any logging via network, nor do I store sensitive data.
